apiVersion: mlpie.ai/v1alpha1
kind: Dataset
metadata:
  name: customers
spec:
  description: "Customer data for Project 2 Prod"
  project: project2
  environment: prod
  format: csv
  source:
    type: file
    path: "/data/p2-prod-customers.csv" 