apiVersion: mlpie.ai/v1alpha1
kind: Project
metadata:
  name: project2
spec:
  description: "Example Project 2"
  # Specify repository for environments
  environments:
    repository:
      url: "https://github.com/mlpie/project2-environments.git"
      ref: "main"
      auth_type: "none" 