apiVersion: mlpie.ai/v1alpha1
kind: Pipeline
metadata:
  name: etl
spec:
  description: "ETL Pipeline for Project 2 Prod"
  project: project2
  environment: prod
  input:
    - dataset: customers
  output:
    dataset: customers_processed
  steps:
    - name: clean
      type: transform
      config:
        script: "clean_data.py" 